#!/usr/bin/env bash
# The Compose stack of the run (project acme-idp-demo), with its secrets kept outside the repository.
#
# The root .gitignore is a given file and does not list `.env`, so no env file is written here: the
# secrets live in ${TMPDIR:-/tmp}/acme-idp-demo.env and are handed to Compose with --env-file
# (goal-brief.md, red line 5; SCOPE.md, "The stack of the run").
#
# Usage: scripts/stack.sh up | down | env | ps
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="${ACME_IDP_ENV_FILE:-${TMPDIR:-/tmp}/acme-idp-demo.env}"

gen() { node -e 'console.log(require("node:crypto").randomBytes(24).toString("base64url"))'; }

ensure_env_file() {
  [ -f "$env_file" ] && return 0
  umask 077
  {
    echo "# Generated by scripts/stack.sh for the Compose project acme-idp-demo."
    echo "# Fresh secrets per run; never copied into the repository."
    echo "KC_BOOTSTRAP_ADMIN_USERNAME=admin"
    echo "KC_BOOTSTRAP_ADMIN_PASSWORD=$(gen)"
    echo "KEYCLOAK_SEED_PASSWORD=$(gen)"
    echo "LOCAL_SEED_PASSWORD=$(gen)"
    for name in ACME_TASKS_SECRET_TENANT_A ACME_TASKS_SECRET_TENANT_B \
                ACME_REPORTS_SECRET_TENANT_A ACME_REPORTS_SECRET_TENANT_B \
                ACME_TASKS_SHORTLIVED_SECRET_TENANT_A ACME_TASKS_SHORTLIVED_SECRET_TENANT_B \
                ACME_TASKS_SYNC_SECRET; do
      echo "$name=$(gen)"
    done
    echo "MONGO_URL=mongodb://127.0.0.1:18417"
    echo "MONGO_DB=acme_tasks"
    echo "KEYCLOAK_BASE_URL=http://localhost:18480"
  } > "$env_file"
  echo "wrote $env_file" >&2
}

case "${1:-up}" in
  up)
    ensure_env_file
    docker compose --env-file "$env_file" -f "$repo_root/compose.yaml" up -d --wait
    # Keycloak imports ${env.NAME} literally (facts.md, F11), so the secrets go in afterwards.
    set -a; . "$env_file"; set +a
    node "$repo_root/scripts/provision.ts"
    ;;
  down)
    ensure_env_file
    docker compose --env-file "$env_file" -f "$repo_root/compose.yaml" down "${@:2}"
    ;;
  seed)
    # The `local` tenant and its password users, into the database the stack runs (T011).
    # Needs node_modules, so it comes after `pnpm install` and not inside `up`.
    ensure_env_file
    set -a; . "$env_file"; set +a
    node "$repo_root/apps/api/src/seed.ts"
    ;;
  ps)
    ensure_env_file
    docker compose --env-file "$env_file" -f "$repo_root/compose.yaml" ps
    ;;
  env)
    ensure_env_file
    echo "$env_file"
    ;;
  *)
    echo "usage: scripts/stack.sh up|down|seed|ps|env" >&2
    exit 2
    ;;
esac
